---
name: Build and Deploy Dev
on:
  push:
    branches: [dev]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build:
    permissions:
      packages: write
      id-token: write
    uses: elastic-ipfs/shared-workflows/.github/workflows/lambda-shared-build.yaml@main
    with:
      docker_image_version_suffix_label: dev
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: us-west-2
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_DEV }}
  deploy:
    uses: elastic-ipfs/shared-workflows/.github/workflows/lambda-shared-deploy.yaml@main
    permissions:
      id-token: write
    needs: build
    with:
      deploy_to_environment: dev
      lambda: dev-ep-event-delivery
      docker_image_version: ${{ needs.build.outputs.build_date }}-dev
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: us-west-2
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_DEV }}
